# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRVtdPob0a1OdOko-dw7Vj93uXBGKUpl
"""

# ==========================================
# IMPLEMENTASI SVC KLASIFIKASI OMSET KOMOKOPI
# ==========================================
# Import Library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns



# ==========================================
# 1. Membaca Dataset
# ==========================================

from google.colab import files

uploaded = files.upload()

# Assuming the uploaded file is a CSV and assigning it to 'data'
# You might need to change 'your_file_name.csv' to the actual name of your uploaded file
for fn in uploaded.keys():
  data = pd.read_csv(fn)


print("Data Komokopi:")
print(data.head())



# ==========================================
# 2. Cek Dataset
# ==========================================

print("\nInformasi Data:")
data.info()
print("\nData Kosong:")
print(data.isnull().sum())


# ==========================================
# 2.1 Preprocessing Non-Numeric Columns
# ==========================================
# Clean 'Rata_Rata_Pembelian' and 'Omset_Harian' columns
# Remove 'Rp' and ',' and convert to numeric
data['Rata_Rata_Pembelian'] = data['Rata_Rata_Pembelian'].str.replace('Rp', '').str.replace(',', '').astype(float)
data['Omset_Harian'] = data['Omset_Harian'].str.replace('Rp', '').str.replace(',', '').astype(float)
print("\nData Setelah Preprocessing Numerik:")
print(data.head())


# ==========================================
# 3. Encoding Data Kategori
# ==========================================

encoder = LabelEncoder()
data["Promo"] = encoder.fit_transform(data["Promo"])
data["Weekend"] = encoder.fit_transform(data["Weekend"])
data["Kategori_Omset"] = encoder.fit_transform(
    data["Kategori_Omset"]
)

print("\nData Setelah Encoding:")
print(data.head())



# ==========================================
# 4. Menentukan Fitur dan Target
# ==========================================
X = data[
    [
        "Jumlah_Pelanggan",
        "Jumlah_Transaksi",
        "Promo",
        "Weekend",
        "Rata_Rata_Pembelian"
    ]
]
y = data["Kategori_Omset"]



# ==========================================
# 5. Membagi Data Training dan Testing
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# ==========================================
# 6. Normalisasi Data
# ==========================================
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



# ==========================================
# 7. Membuat Model SVC
# ==========================================
model = SVC(
    kernel="linear"
)

# Training model
model.fit(
    X_train,
    y_train
)
print("\nModel SVC berhasil dibuat")


# ==========================================
# 8. Prediksi
# ==========================================
y_pred = model.predict(
    X_test
)

# ==========================================
# 9. Evaluasi Model
# ==========================================
print("\nAkurasi Model:")
print(
    accuracy_score(
        y_test,
        y_pred
    )
)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred
    )
)


# ==========================================
# 10. Confusion Matrix
# ==========================================
cm = confusion_matrix(
    y_test,
    y_pred
)
print("\nConfusion Matrix:")
print(cm)


# Grafik Confusion Matrix
plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d"
)


plt.xlabel("Prediksi")
plt.ylabel("Aktual")
plt.title(
    "Confusion Matrix SVC Komokopi"
)
plt.show()


# ==========================================
# 11. Prediksi Data Baru
# ==========================================
data_baru = pd.DataFrame(
    [
        [
            60,     # Jumlah Pelanggan
            50,     # Jumlah Transaksi
            1,      # Promo
            1,      # Weekend
            25000   # Rata-rata Pembelian
        ]
    ],
    columns=[
        "Jumlah_Pelanggan",
        "Jumlah_Transaksi",
        "Promo",
        "Weekend",
        "Rata_Rata_Pembelian"
    ]
)


data_baru = scaler.transform(data_baru)
hasil = model.predict(
    data_baru
)

print("\nHasil Prediksi Kategori Omset:")
print(hasil)