# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRVtdPob0a1OdOko-dw7Vj93uXBGKUpl
"""

# ==========================================
# IMPLEMENTASI SVC KLASIFIKASI OMSET KOMOKOPI
# ==========================================


# Import Library

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sns



# ==========================================
# 1. Membaca Dataset Komokopi
# ==========================================

data = pd.read_csv("dataset_komokopi.csv")


print("Data Awal Komokopi:")
print(data.head())



# ==========================================
# 2. Preprocessing Data
# ==========================================


# Ubah tanggal

data["Tanggal"] = pd.to_datetime(
    data["Tanggal"]
)



# Ubah format Rupiah menjadi angka

data["Rata_Rata_Pembelian"] = (
    data["Rata_Rata_Pembelian"]
    .str.replace("Rp","", regex=False)
    .str.replace(",","", regex=False)
    .astype(float)
)


data["Omset_Harian"] = (
    data["Omset_Harian"]
    .str.replace("Rp","", regex=False)
    .str.replace(",","", regex=False)
    .astype(float)
)



print("\nData Setelah Preprocessing:")
print(data.head())



# ==========================================
# 3. Encoding Data Kategori
# ==========================================

encoder = LabelEncoder()


data["Promo"] = encoder.fit_transform(
    data["Promo"]
)


data["Weekend"] = encoder.fit_transform(
    data["Weekend"]
)


data["Kategori_Omset"] = encoder.fit_transform(
    data["Kategori_Omset"]
)



# ==========================================
# 4. Menentukan Fitur dan Target
# ==========================================


X = data[
    [
        "Jumlah_Pelanggan",
        "Jumlah_Transaksi",
        "Promo",
        "Weekend",
        "Rata_Rata_Pembelian"
    ]
]


y = data["Kategori_Omset"]



# ==========================================
# 5. Membagi Data Training dan Testing
# ==========================================


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



# ==========================================
# 6. Normalisasi
# ==========================================


scaler = StandardScaler()


X_train = scaler.fit_transform(
    X_train
)


X_test = scaler.transform(
    X_test
)



# ==========================================
# 7. Membuat Model SVC
# ==========================================


model = SVC(
    kernel="linear"
)


model.fit(
    X_train,
    y_train
)



print("\nModel SVC berhasil dibuat")



# ==========================================
# 8. Pengujian Model
# ==========================================


prediksi_test = model.predict(
    X_test
)


print("\nAkurasi:")
print(
    accuracy_score(
        y_test,
        prediksi_test
    )
)


print("\nClassification Report:")
print(
    classification_report(
        y_test,
        prediksi_test
    )
)



# ==========================================
# 9. Prediksi Data Bulan 1 - 5
# ==========================================


data_prediksi = data[
    [
        "Jumlah_Pelanggan",
        "Jumlah_Transaksi",
        "Promo",
        "Weekend",
        "Rata_Rata_Pembelian"
    ]
]


data_prediksi = scaler.transform(
    data_prediksi
)



hasil_prediksi = model.predict(
    data_prediksi
)



# Mengubah angka kembali menjadi kategori

hasil_kategori = encoder.inverse_transform(
    hasil_prediksi
)



# ==========================================
# 10. Total Akhir Prediksi Kategori Omset
# ==========================================


hasil_prediksi = model.predict(
    data_prediksi
)


# Ubah angka menjadi kategori

hasil_kategori = encoder.inverse_transform(
    hasil_prediksi
)


# Menghitung jumlah tiap kategori

hasil_total = pd.Series(
    hasil_kategori
).value_counts()


print("\nTotal Prediksi Kategori Omset Komokopi Bulan 1-5:")

print(hasil_total)



# Menentukan kategori terbanyak

kategori_akhir = hasil_total.idxmax()


print("\nKategori Omset Akhir Komokopi Bulan 1-5:")

print(kategori_akhir)